import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Nav from "./components/Nav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <head>
        <title>{metadata.title}</title>
        {/* Include font import or other global imports here */}
      </head>
      <body>
        <Providers>
          <Nav />
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
